services:
  risk-engine:
    image: risk-engine:local
    build:
      context: .
    environment:
      SERVER_PORT: 8089
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
    ports: ["8089:8089"]
networks:
  default:
    name: acquiring-net